# Generated by Django 3.0.7 on 2020-07-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Review',
        ),
    ]
