# Generated by Django 3.0.7 on 2020-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200713_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
