# Generated by Django 3.0.7 on 2020-07-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actor_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
