# Generated by Django 3.0.8 on 2020-07-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200726_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
